# -*- coding: utf-8 -*-
"""Meridian Global Enterprise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpJextejNGCJ3BT5gcjKiYEdarEV7U5_

# HR Service Delivery & Master Data Management (MDM) Pipeline

**Company:** Meridian Global Enterprise

## Business Problem Statement
Meridian Global Enterprise recently centralized its HR Service Delivery operations to manage human resources and payroll services for a global workforce of 1,500 employees. However, leadership has identified two critical operational failures within the new support model:

1. **Master Data Corruption:** The legacy system extract is plagued by poor data governance. Unstandardized department names, duplicate employee records, and corrupted timestamp formats are preventing accurate reporting across cross-functional systems.
2. **Service Level Agreement (SLA) Breaches:** Employees and managers are reporting severe delays in ticket resolution. Critical HR data requests are routinely failing to be processed within the mandated End-of-Day SLA, causing downstream friction with payroll and daily operations.

## Project Objective
As the Workforce Data Admin, the objective is to build an automated ETL pipeline to resolve these operational failures and establish a single source of truth.

* **Extract & Transform (Python):** Ingest the raw HR ticketing and employee master datasets. Enforce strict Master Data Management (MDM) rules to clean string inconsistencies, remove duplicates, and standardize corrupted date formats.
* **Load & Analyze (SQL):** Construct relational queries to mathematically calculate ticket resolution times and flag SLA breaches based on End-of-Day business logic.
* **Visualize (Tableau):** Develop an operational dashboard to track HR agent performance, monitor request volumes, and pinpoint the exact workflow bottleneck causing critical escalations to fail.
"""

# Importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# importing dataset

df_employee = pd.read_csv('/content/employee_master.csv')
df_tickets = pd.read_csv('/content/hr_service_tickets.csv')

df_list = [df_employee, df_tickets]

df_employee.head()

df_tickets.head()

print(df_employee.shape)
print(df_tickets.shape)

# checking column dtype and null

for i in df_list:
  print(i.info())

"""-- only resolved at column contains null values colud be non resolved tickets will verify on further analysis"""

# checking number of unique values inside each column
print('number_of unique values')
for i in df_list:
  print(i.nunique())
  print('==' * 5)

# checking unique values inside categorical columns

emp_cat = ['dept.','Office Location','Emp Status']

print('employees')
print('==' * 5)
for i in emp_cat:
  print(i,':  ', df_employee[i].unique())

ticket_cat = ['Request Topic','Priority Level', 'Agent Group', 'Ticket Status' ]
print()
print('tickets')
print('==' * 5)
for i in ticket_cat:
  print(i,':  ', df_tickets[i].unique())

# verifying if the null values in resolved at is the In Progress tickets

(df_tickets['Resolved At'].isna().all() == df_tickets[df_tickets['Ticket Status'] == 'In Progress'].all())

# column names are in differnt formates standardizing column naming

# Function to clean and apply snake_case to column names
for df in [df_employee, df_tickets]:
    df.columns = (df.columns
                  .str.strip()                                  # Remove leading/trailing white spaces
                  .str.lower()                                  # Convert to lowercase
                  .str.replace(r'[^\w\s]', '', regex=True)      # Remove special characters (like # and .)
                  .str.replace(r'\s+', '_', regex=True))        # Replace remaining spaces with underscores

# Verify the changes
print("--- Cleaned Employee Master Columns ---")
print(df_employee.columns.tolist())

print("\n--- Cleaned Tickets Data Columns ---")
print(df_tickets.columns.tolist())

# department column contains inconsitant data fixing it

dept_mapping = {
    ' HR ': 'Human Resources',
    'Human Res': 'Human Resources',
    'hr': 'Human Resources',
    'Ops': 'Operations',
    'Operations': 'Operations',
    'Fin': 'Finance',
    'Finance': 'Finance',
    'Sales': 'Sales'
}


df_employee['dept'] = df_employee['dept'].replace(dept_mapping)


print("--- Cleaned Department Values ---")
print(df_employee['dept'].value_counts())

# checking date formats
date_columns = ['created_on', 'sla_deadline', 'resolved_at']

print("--- Date Format Audit ---")
for col in date_columns:
    # Attempt to convert to datetime, coercing bad formats to NaT
    temp_converted = pd.to_datetime(df_tickets[col], errors='coerce')

    # Find rows where the original value is NOT null, but the conversion resulted in NaT
    invalid_dates = df_tickets[(df_tickets[col].notna()) & (temp_converted.isna())]

    print(f"\nColumn: '{col}'")
    print(f"Total invalid date values found: {len(invalid_dates)}")

    # If invalid values exist, print a few unique examples to see what we are dealing with
    if len(invalid_dates) > 0:
        print(f"Examples of corrupted strings: {invalid_dates[col].unique()[:5]}")

"""### Date Formatting Issues found & Resolutions

During the initial inspection of the **created_on** column in the ticketing dataset, we identified 755 invalid date strings. These anomalies fall into two distinct categories requiring different data cleaning strategies:

**1. Mixed Date Formats (EU vs. US)**
* **The Insight:** A significant portion of the dates are completely valid but formatted using the European standard (DD-MM-YYYY instead of MM-DD-YYYY).
* **The Resolution:** Convert it to MM-DD-YYYY.

**2. Invalid dates('########')**
* **The Insight:** A subset of the rows contains the literal string `'########'`.
* **The Resolution:** Because the SLA deadlines follow strict End-of-Next-Business-Day rules, we can reverse-engineer the creation day by subtracting one business day from the known **sla_deadline**.
"""

from pandas.tseries.offsets import BDay

# ==========================================
# 1. Parse Dates and Handle EU Formats
# ==========================================
# errors='coerce' forces '########' to NaT. dayfirst=True parses the EU dates correctly.
df_tickets['created_on'] = pd.to_datetime(df_tickets['created_on'], errors='coerce', dayfirst=True)
df_tickets['sla_deadline'] = pd.to_datetime(df_tickets['sla_deadline'])
df_tickets['resolved_at'] = pd.to_datetime(df_tickets['resolved_at'])

# ==========================================
# 2. Reverse-Engineer Missing Dates ('########')
# ==========================================
# Create a mask to find exactly where the NaT (previously '########') values are
missing_mask = df_tickets['created_on'].isna()

# Subtract 1 Business Day from the SLA Deadline for those specific rows
imputed_dates = df_tickets.loc[missing_mask, 'sla_deadline'] - BDay(1)

# The SLA deadline is at 23:59:59. We normalize it (strips the time to 00:00:00)
# and add exactly 9 hours to simulate a standard 09:00:00 AM ticket creation time.
df_tickets.loc[missing_mask, 'created_on'] = imputed_dates.dt.normalize() + pd.Timedelta(hours=9)

# ==========================================
# 3. Verify the Fix
# ==========================================
print("--- Date Standardization Audit ---")
print(f"Remaining nulls in 'created_on': {df_tickets['created_on'].isna().sum()}")
print(f"Total rows in ticketing dataset: {len(df_tickets)}")

# Display a few of the newly imputed rows to confirm the 9:00 AM logic worked perfectly
print("\nSample of Reverse-Engineered Dates:")
display(df_tickets[missing_mask][['created_on', 'sla_deadline']].head())

